### ISSUE TITLE
Messages Order is not right

### ISSUE THREAD

**Issue by mohammedaminA** [londonappbrewery/Flash-Chat-Flutter-Complete#21]
.reversed is not working for some reason and the messages still appear in a strange order. Rather what should be done is create a Timestamp field along with text and sender. The timestamp can then be used to order the messages using orderBy('time': descending: false)

**Comment by JAZZKIT** [comment]
> .reversed is not working for some reason and the messages still appear in a strange order. Rather what should be done is create a Timestamp field along with text and sender. The timestamp can then be used to order the messages using orderBy('time': descending: false)

Thanks. Also, it will be helpful https://stackoverflow.com/questions/55025301/using-startat-from-firebase-with-flutter-timestamps
