### ISSUE TITLE
The animated title in welcome screens animates to fast and only animates for three times.

### ISSUE THREAD

**Issue by shubha360** [londonappbrewery/Flash-Chat-Flutter-Complete#5]
Here is the code

`TypewriterAnimatedTextKit(
                  text: ['Flash Chat'],
                  textStyle: TextStyle(
                    fontSize: 45.0,
                    fontWeight: FontWeight.w900,
                  ),
                ),`

**Comment by coder-unknown** [comment]
Add speed parameter to AnimatedTextKit.
`speed: Duration(seconds: 1),`
